INSERT INTO person (DOCUMENT, FINGERPRINT, BLACKLIST) VALUES ('10000000', TRUE, FALSE);
INSERT INTO person (DOCUMENT, FINGERPRINT, BLACKLIST) VALUES ('10000001', FALSE, FALSE);
INSERT INTO person (DOCUMENT, FINGERPRINT, BLACKLIST) VALUES ('10000002', TRUE, TRUE);